# Generated by Django 3.0.6 on 2020-05-21 19:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0002_usertask'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usertask',
            old_name='username',
            new_name='user',
        ),
    ]
