# Generated by Django 3.0.6 on 2020-05-22 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0006_auto_20200522_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='taskApp.UserCustom'),
        ),
    ]
