# Generated by Django 3.0.6 on 2020-05-23 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskApp', '0008_auto_20200522_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usertask',
            name='label',
            field=models.CharField(max_length=264, unique=True),
        ),
    ]
